"""empty message

Revision ID: ef962de00c9c
Revises: 82164b9cf5c8
Create Date: 2022-02-02 08:02:20.920101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef962de00c9c'
down_revision = '82164b9cf5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_jogging_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', mysql.TIME(), nullable=False),
    sa.Column('location', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('weather_condition', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('IDX_user_ids', 'user_jogging_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IDX_user_ids', table_name='user_jogging_data')
    op.drop_table('user_jogging_data')
    # ### end Alembic commands ###
